name = "sematic-video-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sematic"
database_id = "f0ba94b8-e45c-4e2f-8d20-63fbf4b42721" 

[ai]
binding = "AI"

[[r2_buckets]]
binding = "videos"
bucket_name = "sematic-videos"

[[r2_buckets]]
binding = "audios"
bucket_name = "sematic-audios"

[[r2_buckets]]
binding = "frames"
bucket_name = "sematic-frames"

[[queues.producers]]
binding = "video_segment_queue"
queue = "video-segment-queue"

[vars]
FFMPEG_API_URL = "https://sematic-video-884913204584.europe-west1.run.app"